export const myDeck = ([

    {
        keyNum: 1,
        cardColor: '#00eeff',
        topic: 'Exposition',
        title: `Misha Kahn's Furniture Unhinged`,
        stage: 'Breggio Plaza',
        date: 'Aug 2022',
        time: '20:00 EST',
        code: 'M',
        imag: 'https://media.architecturaldigest.com/photos/61d32b267a58c403a95c550d/master/w_1600,c_limit/Lot%209_It%20Must%20Have%20Been%20the%20Clams%20(Chair).jpg',
    },
    {
        keyNum: 2,
        cardColor: '#f4446f',
        topic: 'First Hate',
        title: 'Commercial New Video Premiere',
        stage: 'Troya Stage',
        date: 'July 2022',
        time: '08:00 EST',
        code: 'U',
        imag: 'https://lastfm.freetls.fastly.net/i/u/770x0/08c91a4b4cf31138e6bf47735de9db14.jpg#08c91a4b4cf31138e6bf47735de9db14',
    },
    {
        keyNum: 3,
        cardColor: '#dee153',
        topic: 'Machine Girl',
        title: 'Machine Girl: Neon White OST 2 The Burn That Cures',
        stage: 'Warewolf Stage',
        date: 'June 2022',
        time: '12:00 EST',
        code: 'P',
        imag: 'https://f4.bcbits.com/img/a1100280912_16.jpg',
    },
    {
        keyNum: 4,
        cardColor: '#1144ff',
        topic: 'Bertjan Pot',
        title: 'Mask Exposition',
        stage: 'Green Room',
        date: 'Apr 2022',
        time: '08:00 EST',
        code: 'U',
        imag: 'https://www.stirpad.com/images/news/bertjan-pot-lights-masks-his-emotions-in-his-latest-exhibition_220516074023_1.jpg',
    },
    {
        keyNum: 5,
        cardColor: '#ff4433',
        topic: 'Kitasenju Design',
        title: 'Dance Interactive Experience',
        stage: 'Digital Garden',
        date: 'May 2022',
        time: '12:00 EST',
        code: 'P',
        imag: 'https://kitasenju.design/img/arFlowers.jpg',
    },

]);